[project]
name = "chris-mcp"
version = "0.1.0"
dependencies = []

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
[tool.mcp]
sampling_callback = "llm_handler:handle_sampling_message"
